config/routes.rb
Merged::Engine.routes.draw do

  get  'changes/index'
  post 'changes/commit'
  post 'changes/reset'
  get "styles/index"

  post 'form/sendit'

  resources :pages , except: [:edit , :new] , shallow: true  do
    resources :sections do
      get :set_image
      get :select_template
      get :set_template
      get :select_card_template
      get :set_card_template
      get :move
      resources :cards do
        get :set_image
        get :move
      end
    end
  end
  resources :images do
    get :copy
    post :crop
    post :scale
  end
end

app/models/merged/active_base.rb
module Merged
  class ActiveBase < ActiveYaml::Base
    fields :updated_at , :updated_by

    def edit_save( editor )
      self.updated_at = Time.now
      self.updated_by = editor
      edit_save!(editor)
    end

    def edit_save!(editor)
      ChangeSet.current.edit(self.class.name , self.change_name, editor)
      save!()
      self.class.save_all
    end

    def add_save( editor )
      self.updated_at = Time.now
      self.updated_by = editor
      add_save!(editor)
    end

    def add_save!(editor)
      ChangeSet.current.add(self.class.name , self.change_name, editor)
      save!()
      self.class.save_all
    end

    def delete_save!(editor)
      ChangeSet.current.delete(self.class.name , self.change_name,editor)
      self.class.delete(self.id)
      self.class.save_all
    end

    def self.save_all
      data = @records.collect {|obj| obj.attributes}
      File.write( self.full_path , data.to_yaml)
      self.reload(true)
    end

    def self.delete(id) # only works with id's
      @record_index.delete(id.to_s)
      @records.delete_if{|record| record[:id] == id.to_i}
      true
    end

  end
end

app/models/merged/card.rb
module Merged

  class Card < ViewBase

    belongs_to :section , class_name: "Merged::Section"

    fields  :id , :index , :section_id
    fields  :text , :header, :image_name

    def move_up
      swap_index_with(next_card)
    end

    def change_name
      pagename = section ? section.page.name : section_id.to_s
      "#{pagename}:#{header}"
    end

    def move_down
      swap_index_with(previous_card)
    end

    def previous_card
      section.cards.where(index: index - 1).first
    end

    def next_card
      section.cards.where(index: index + 1).first
    end

    # card templates are stored in the section so the all cards
    # have the same
    def template
      section.card_template
    end

    def template_style
      CardStyle.find_by_template( self.template )
    end

    def delete_and_reset_index(editor)
      delete_save!(editor)
      section.reset_index
      Section.find(section_id).reset_index
      Card.save_all
    end

    def self.new_card(card_template , section_id , index)
      data = { section_id: section_id , index: index}
      template = CardStyle.find_by_template( card_template )
      template.fields.each do |key|
        data[key] = "NEW"
      end
      card = Card.new(data)
      card.add_default_options(template.options_definitions)
      card
    end

  end
end

app/models/merged/card_style.rb
module Merged
  class CardStyle < Style
    
    fields  :template , :text , :header, :fields

    def card_preview
      "merged/card_preview/" + template
    end

  end
end

app/models/merged/change_set.rb
module Merged
  class ChangeSet


    def self.current
      @@current ||= ChangeSet.new
    end
    attr_reader :adds , :edits , :deletes , :last , :last_editor

    def initialize
      zero
    end

    def zero
      [Page, Section, Card].each { |m| m.reload(true) }
      @adds = Set.new
      @edits = Set.new
      @deletes = Set.new
      @last = nil
      @last_editor = nil
    end

    def touch(editor)
      @last = Time.now
      @last_editor = editor
    end

    def add( type , text , editor)
      touch(editor)
      @adds << [typed(type) , text ]
    end

    def edit( type , text, editor)
      touch(editor)
      @edits << [typed(type) , text ]
    end
    def delete( type , text, editor)
      touch(editor)
      @deletes << [typed(type) , text ]
    end

    def added( type )
      type = type.to_sym
      @adds.select { |a| a.first == type }
    end
    def edited( type )
      type = type.to_sym
      @edits.select { |a| a.first == type }
    end
    def deleted( type )
      type = type.to_sym
      @deletes.select { |a| a.first == type }
    end

    def typed(class_name)
      class_name.split("::").last.to_sym
    end
  end
end

app/models/merged/image.rb
require "mini_magick"
require "fileutils"

module Merged
  class Image < ActiveBase

    set_root_path Rails.root

    fields  :name , :tags , :type , :size ,  :height , :width

    def change_name
      name
    end

    def aspect_ratio
      ratio = self.ratio
      ratios = (1..9).collect{ |i|  ((ratio * i) - (ratio * i).round(0)).abs }
      min , min_index = ratios.each_with_index.min
      [(ratio *  (min_index + 1) ).round(0).to_i , (min_index + 1) ]
    end

    def ratio
      return 0 unless self.height
      self.width.to_f / self.height
    end

    def copy()
      image = Image.new name: "#{name}_copy" , type: type , tags: (tags || "")
      Image.insert(image) # assigns next id
      FileUtils.cp full_filename , image.full_filename
      image.init_file_data
      image
    end

    #save an io as new image. The filename is the id, type taken from io
    def self.create_new(name , tags,  io)
      original , ending = io.original_filename.split("/").last.split(".")
      name = original if( name.blank? )
      image = Image.new name: name , type: ending , tags: (tags || "")
      self.insert(image) # assigns next id
      full_filename = image.id.to_s + "." + ending
      File.open(Rails.root.join("app/assets/images/cms/", full_filename), "wb") do |file|
        file.write( io.read )
      end
      image.init_file_data
      image
    end

    def init_file_data
      image = MiniMagick::Image.new(full_filename)
      self.width = image.width
      self.height = image.height
      self.size = (image.size/1024).to_i
    end

    def destroy(editor)
      File.delete self.full_filename
      delete_save!(editor)
    end

    def asset_name
      image_root + "/" + self.id.to_s + "." + self.type
    end

    def full_filename
      full_filename = self.id.to_s + "." + self.type
      Rails.root.join(asset_root, full_filename)
    end

    def self.transform
      Image.all.each do |image|
        last = image.name.split.last
        image.tags = ""
        ["wide", "small" , "big" , "room"].each do |tag|
          if(last == tag)
            image.name = image.name.gsub(last,"").strip
            image.tags = last
          end
        end
        image.save
      end
    end

    def self.root
      "app/assets/images/cms"
    end

    private

    def asset_root
      "app/assets/images/" + image_root
    end

    def image_root
      "cms"
    end

  end
end

app/models/merged/option.rb
module Merged
  class Option < ActiveYaml::Base
    set_root_path Engine.root + "config"

    fields :name , :default , :description , :values , :type

    def type
      return attributes[:type] unless attributes[:type].blank?
      if has_values?
        "select"
      else
        "text"
      end
    end

    def has_values?
      return false if attributes[:values].nil?
      ! attributes[:values].empty?
    end

    def values
      return [] unless has_values?
      attributes[:values].split(" ")
    end

  end
end

app/models/merged/option_definition.rb
module Merged
  class OptionDefinition < ActiveBase
    set_root_path Engine.root + "config"

    fields :name , :default , :description , :values , :type

    def type
      return attributes[:type] unless attributes[:type].blank?
      if has_values?
        "select"
      else
        "text"
      end
    end

    def has_values?
      return false if attributes[:values].nil?
      ! attributes[:values].empty?
    end

    def values
      return [] unless has_values?
      attributes[:values].split(" ")
    end

  end
end

app/models/merged/optioned.rb
module Merged
  #relies only on @content["options"]
  #and a method template_style
  # and index
  # and is due for a rename

  module Optioned
    def has_option?(option)
      options.has_key?(option) and !options[option].blank?
    end

    def option_definitions
      template_style.options_definitions
    end

    def option(name)
      options[name]
    end

    def options
      return attributes[:options] unless attributes[:options].blank?
      attributes[:options] = {}
    end

    def set_option( option , value)
      options[option] = value
    end

    def add_default_options( definitions = nil )
      definitions = option_definitions if definitions.nil?
      definitions.each do |option|
        next unless option.default
        set_option( option.name , option.default)
      end
    end

    def update(key , value)
      raise "unsuported field #{key} for #{template}" unless allowed_fields.include?(key)
      if(! attributes[key].nil? ) # first setting ok, types not (yet?) specified
        if( @attributes[key].class != value.class )
          raise "Type mismatch #{key} #{key.class}!=#{value.class}"
        end
      end
      attributes[key] = value
    end

    #other may be nil
    def swap_index_with(other)
      return unless other
      old_index = self.index
      self.index = other.index
      other.index = old_index
    end

    def allowed_fields
      template_style.fields.collect{|f| f.to_sym}
    end

  end
end

app/models/merged/page_style.rb
module Merged
  class PageStyle < Style
    fields  :type , :description , :section_template

    def section_preview
      "merged/section_preview/" + section_template
    end

  end
end

app/controllers/merged/application_controller.rb
module Merged
  class ApplicationController < ActionController::Base
  end
end

app/controllers/merged/cards_controller.rb
module Merged
  class CardsController < MergedController
    before_action :set_card , except: [:index , :new]

    def index
      @section = Section.find(params[:section_id])
    end

    def set_image
      @card.image_id = params[:image_id].to_i
      @card.edit_save(current_member.email)
      message = @card.image ? "#{@card.image.name} selected" : "Image removed"
      redirect_to section_cards_url(@card.section.id) , notice: message
    end

    def move
      if( params[:dir] == "up")
        @card.move_up
      else
        @card.move_down
      end
      @card.edit_save(current_member)
      redirect_to section_cards_url(@card.section.id),notice: "#{@card.header} moved"
    end

    def new
      @section = Section.find(params[:section_id])
      new_card =  @section.new_card
      new_card.add_save(current_member.email)
      redirect_to section_cards_url(@section.id) , notice: "Card created"
    end

    def destroy
      @card.delete_and_reset_index(current_member.email)
      redirect_to section_cards_url(@card.section.id) , notice: "#{@card.header} removed"
    end

    def update
      @card.allowed_fields.each do |key|
        if( params.has_key?(key) )
          @card.update(key, params[key])
        end
      end
      options = params[:option]
      @card.option_definitions.each do |option|
        @card.set_option(option.name,  options[option.name])
      end if options
      @card.edit_save(current_member.email)
      redirect_to section_cards_url(@card.section.id) , notice: "Updated #{@card.header}"
    end

    private
    def set_card
      card_id = params[:id] || params[:card_id]
      @card = Card.find( card_id )
    end

  end
end

app/controllers/merged/changes_controller.rb
require "git"

module Merged
  class ChangesController < MergedController

    def index
      @git = Git.open(Rails.root)
      @status = @git.status()
    end

    def commit
      if params[:message].blank?
        message = "must have message"
        redirect_to changes_index_url , alert: message
      else
        git = Git.open(Rails.root)
        git.add("merged")
        git.add( Image.root )
        begin
          g.config('user.email', current_member.email)
          git.commit(params[:message])
          redirect_to changes_index_url , notice: "Changes commited"
        rescue
          redirect_to changes_index_url , notice: "Error occurred"
        end
      end
    end

    def reset
      git = Git.open(Rails.root)
      begin
        git.checkout_file("HEAD" , "merged")
        git.checkout_file("HEAD" , "app/assets/images/cms")
        ChangeSet.current.zero
        message = "Changes reset"
      rescue
        message = "Unknown error occured"
      end
      redirect_to changes_index_url , notice: message
    end

  end
end

app/controllers/merged/cms_controller.rb
module Merged
  class ViewController < ApplicationController

    def view
      page = params[:id]
      # assert file exists
      @data = YAML.load_file(Rails.root.join('merge' , "#{page}.yaml"))
      #assert data is an array (of hashes?)
    end

  end
end

app/controllers/merged/form_controller.rb
module Merged
  class FormController < MergedController

    def sendit
      @section = Section.find( params[:section_id] )
      @errors = { }
      return if bot_alert
      check_maths
      verify_data
      if( @errors.length > 0)
        render :form
      else
        dispatch_form_data( )
        redirect_to main_app.root_url , notice: @section.option("ok_message")
      end
    end

    private

    def dispatch_form_data
      puts "Dispatch data"
      data = {}
      @section.cards.each do |card|
        data[card.header] = params[card.header]
      end
      if(@section.has_option?("handler") )
        puts "Sending data"
        @section.option("handler").constantize.new.handle_form(@section, data)
      end
    end

    def verify_data
      @section.cards.each do |card|
        check_option( card , params[card.header])
      end
    end
    def check_option(card , value)
      return unless value.blank?
      puts "Checking #{card.header} #{value}"
      compulsory = card.option("compulsory") != "no"
      return unless compulsory
      # check different types
      message = card.text
      message = "May not be empty" if message.blank?
      @errors[card.header] = message
    end

    def check_maths
      key = params[:bot_fudder].to_i / 2
      if( (2*key + 1).to_s != params[:challenge])
        @errors[:challenge] = "Check the maths #{params[:challenge]}"
      end
    end

    def bot_alert
      if @section.nil?
        head :ok
        return true
      end
      key = params[:bot_fudder]
      if key.to_i.to_s != key
        head :ok
        return true
      end
      return false
    end
  end
end

app/controllers/merged/images_controller.rb
require "mini_magick"

module Merged
  class ImagesController < MergedController
    before_action :set_image, only: %i[ update destroy show scale crop copy ]

    def index
      @images = Image.all
      @image_data = @images.collect{|i|
        data = i.attributes.dup
        data[:url] = view_context.asset_path(i.asset_name)
        data[:link] = build_select_link_for(i)
        data[:updated_at] = i.updated_at.to_date if i.updated_at
        data[:created] = i.updated_at.to_i
        data[:aspect_ratio] = i.aspect_ratio.join("/")
        data[:ratio] = i.aspect_ratio
        data
      }
    end

    def destroy
      @image.destroy(current_member.email)
      redirect_to :images , notice: "Image #{@image.name} deleted"
    end

    def update
      @image.name = params[:name]
      @image.tags = params[:tags]
      @image.edit_save(current_member.email)
      redirect_to image_path(@image) , notice: "Image updated"
    end

    def scale
      mini = MiniMagick::Image.new( @image.full_filename)
      mini.resize( "#{params[:scale]}%")
      @image.init_file_data
      @image.edit_save(current_member.email)
      redirect_to image_path(@image) , notice: "Image was scaled"
    end

    def crop
      mini = MiniMagick::Image.new( @image.full_filename)
      size = "#{params[:size_x]}x#{params[:size_y]}+#{params[:off_x]}+#{params[:off_y]}"
      mini.crop( size )
      @image.init_file_data
      @image.edit_save(current_member.email)
      redirect_to image_path(@image) , notice: "Image was resized"
    end

    def show
      @sections = Section.where(image_id: params[:id].to_i)
      @cards = Card.where(image_id: params[:id].to_i)
      @used = ((@cards.length > 0) || (@sections.length > 0))
      @image_data = @image.attributes
    end

    def copy
      image = @image.copy
      image.add_save(current_member.email)
      redirect_to image_path(image.id) , notice: "Image copied"
    end

    def create
      image = Image.create_new(params['filename'] ,params['tags'], params['image_file'])
      image.add_save current_member.email
      where_to  = determine_redirect(image)
      redirect_to where_to , notice: "New image created: #{image.name}"
    end

    private

    def set_image
      @image = Image.find(params[:id] || params[:image_id])
    end
    def determine_redirect(image)
      if(params[:section_id])
        view_context.section_set_image_url(params[:section_id],image_id: image.id )
      elsif(params[:card_id])
        view_context.card_set_image_url(params[:card_id],image_id: image.id )
      else
         :images
      end
    end

    def build_select_link_for(image)
      if(params[:section_id])
        return view_context.section_set_image_url(params[:section_id] , image_id: image.id)
      end
      if(params[:card_id])
        return view_context.card_set_image_url(params[:card_id] , image_id: image.id)
      end
      view_context.image_url(image.id)
    end
  end

end

app/views/merged/sections/_form.html.haml
= form_for @merged_section do |f|
  - if @merged_section.errors.any?
    #error_explanation
      %h2= "#{pluralize(@merged_section.errors.count, "error")} prohibited this merged_section from being saved:"
      %ul
        - @merged_section.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/merged/sections/_option_form_date.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= select_date section.option(option.name) , :prefix => "option[#{option.name}]"

app/views/merged/sections/_option_form_select.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= select_tag( "option[#{option.name}]" , options_for_select(option.values, section.option(option.name)), class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")

app/views/merged/sections/_option_form_text.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= text_field_tag( "option[#{option.name}]" , section.option(option.name), class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")

app/views/merged/sections/_sections_pagination.haml
.text-xl.font-bold.text-gray-900
  = section.page.type.capitalize
  =link_to section.page.name, merged.page_sections_path(section.page.id), class: "underline"
.inline-flex.items-center.justify-center.gap-3
  .text-xl.font-bold.text-gray-900
    Section #{section.header}
  - if section.previous_section
    =link_to merged.section_path(section.previous_section.id) , class: "inline-flex h-8 w-8 items-center justify-center rounded border border-gray-100 hover:bg-sky-100" do
      %span.sr-only Next Section
      %svg.h-3.w-3{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z", "fill-rule" => "evenodd"}
  - else
    .inline-flex.h-8.w-8.items-center.justify-center.rounded.border.border-gray-100
  %p.text-xs
    = section.index
    %span{:class => "mx-0.25"} /
    = section.page.sections.length
  - if section.next_section
    =link_to merged.section_path(section.next_section.id), class: "inline-flex h-8 w-8 items-center justify-center rounded border border-gray-100 hover:bg-sky-100" do
      %span.sr-only Next Section
      %svg.h-3.w-3{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z", "fill-rule" => "evenodd"}
  - else
    .inline-flex.h-8.w-8.items-center.justify-center.rounded.border.border-gray-100

app/views/merged/sections/index.html.haml
- content_for( :merged_menu ) do
  .text-xl.font-bold.text-gray-900
    Page
    = @page.name
  .text-xl.text-gray-900
    =link_to "View live" , "/#{@page.name}" , target: @page.name

= render "layouts/merged_header"

-@page.sections.each do |section |
  .flex.gap-10.p-4{class: (section.index%2)==1 ? 'bg-cyan-50' : 'bg-red-50' , id: "section_#{section.id}"}
    .basis-80
      %h3.mt-4.text-lg.font-bold Section #{section.index} : #{section.header}
      = blue_button( "Up" , section_move_url(section.id , dir: :up) )
      = blue_button( "Down" , section_move_url(section.id , dir: :down) )
      = yellow_button("Edit" , section_path(section.id) )
      = green_button( "Copy" , new_page_section_url(@page.id, template: section.template) )
      = form_tag( section_url(section.id) , {method: :delete  } ) do
        =submit_button( "Delete" , true)
    .basis-72
      %h3.mt-4.text-lg.font-bold Template
      = link_to(section_select_template_url(section.id)) do
        %p= section.template
        = section_preview(section , class: "object-contain")
    .basis-52.grow
      %h3.mt-4.text-lg.font-bold Header
      %p= section.header
      %h3.mt-4.text-lg.font-bold Text
      %p= section.text[0..100] + " ..." if section.text
    .basis-72
      - if section.has_cards?
        %h3.mt-4.text-lg.font-bold #{section.cards.length} Cards
        =link_to section_cards_url(section.id) do
          =card_preview(section , class: "object-contain")
      - else
        = link_to(section_select_image_url(section.id)) do
          %h3.mt-4.text-lg.font-bold Image
          -if section.image
            = image_tag( "cms/" + section.image , class: "h-40")
          -else
            %p No image
    .basis-52.grow
      %h3.mt-4.text-lg.font-bold Options
      - section.options.each do|name , value|
        %p
          = name
          = value
.grid.grid-cols-2.gap-2.m-8
  .relative.block
    %p
      = green_button( "New Section" , new_page_section_url(@page.id) )
  .relative.block
    %p
      = form_tag( page_url(@page.id) , {method: :delete  } ) do
        =submit_button( "Delete Page" , true)

app/views/merged/sections/new.haml
.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Changes
  .text-xl.text-gray-900
    Branch
    = @git.current_branch

%h1 New merged_section

= render 'form'

= link_to 'Back', merged.sections_path

app/views/merged/sections/new.html.haml
- content_for( :merged_menu ) do
  .text-xl.font-bold.text-gray-900
    Changes
  .text-xl.text-gray-900
    Branch
    = @git.current_branch

= render "layouts/merged_header"

%h1 New merged_section

= render 'form'

= link_to 'Back', sections_path

app/views/merged/sections/select_card_template.haml
.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Page #{link_to @section.page.name, merged.page_sections_path(@section.page.id), class: "underline"}
  .text-xl.text-gray-900
    Select Card Style for Section #{@section.index} - #{@section.header}

.grid.grid-cols-4.gap-6.m-8
  - @cards.each do |style|
    .border.border-gray-300.rounded-lg.p-2
      = link_to( merged.section_set_card_template_path( card_template: style.template )) do
        .font-bold.text-lg.text-center.pb-4= style.header
        =image_tag(style.card_preview , class: "w-full object-contain")

app/views/merged/sections/select_template.haml
.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Page #{link_to @section.page.name, merged.page_sections_path(@section.page.id), class: "underline"}
  .text-xl.text-gray-900
    Select Style for Section #{@section.index} - #{@section.header}

.grid.grid-cols-4.gap-6.my-10.mx-20
  - @sections.each do |style|
    .border.border-gray-300.rounded-lg.p-2
      = link_to( merged.section_set_template_path( template: style.template )) do
        .font-bold.text-lg.text-center.pb-4= style.header
        =image_tag(style.section_preview , class: "w-full object-contain")

app/views/merged/sections/show.html.haml
- content_for( :merged_menu ) do
  .text-xl.font-bold.text-gray-900
    Page #{link_to @section.page.name, page_sections_url(@section.page.id), class: "underline"}
  .text-xl.text-gray-900
    Section #{@section.index} / #{@section.page.sections.length} : #{@section.header}
    - if @section.previous_section
      =link_to "(prev)" , section_url(@section.previous_section.id)
    - if @section.next_section
      =link_to "(next)" , section_url(@section.next_section.id)

= render "layouts/merged_header"

- template = find_template(@section)
= render( template , section: @section)

.grid.grid-cols-3.gap-2.m-8
  .relative.block.border.border-gray-100
    %h3.mt-4.text-lg.font-bold Template  #{@section.template}
    = section_preview(@section , class: "w-full object-contain p-3")
    = yellow_button( "Change Template" , section_select_template_url(@section.id))
    = green_button( "New Section" , new_page_section_url(@section.page.id , template: @section.template) )

  .relative.block.border.border-gray-100
    = section_form( class: "mx-auto mt-8 mb-0 max-w space-y-4") do
      %label.block
        %h4.text-lg.font-bold Header
        = text_field_tag( :header , @section.header, class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")
      %label.block
        %h4.mt-4.text-lg.font-bold Text
        = text_area_tag( :text , @section.text, rows: 5 ,class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")
      = submit_button("Update")

  .relative.block.border.border-gray-100
    %h3.mt-4.text-lg.font-bold Image
    -if( @section.image.blank? )
      %p No image
    -else
      = image_tag( "cms/" + @section.image , class: "p-3")
    = yellow_button("Change Image", section_select_image_url(@section.id))
    = red_button( "Remove image", section_set_image_path( @section.id  , image: ""))

.grid.grid-cols-3.gap-2.m-8
  - if( @section.has_cards? )
    .relative.block.border.border-gray-100
      %h3.mt-4.text-lg.font-bold Card Template #{@section.card_template}
      =card_preview(@section , class: "w-full object-contain")
      %p.p-3
        =yellow_button("Change Card Template", section_select_card_template_url(@section.id))

    .relative.block.border.border-gray-100
      %h3.mt-4.text-lg.font-bold #{@section.cards.length} Cards
      -@section.cards.each do |card|
        .mt-4.text-md.font-bold= card.header
        .text-sm #{card.text[0..70]} .....
      %p.p-3
        = yellow_button( "View and Edit Cards" , section_cards_url(@section.id))
        = green_button( "New Card" , new_section_card_url(@section.id) )

  .relative.block.border.border-gray-100
    %h3.mt-4.text-lg.font-bold Options
    = section_form( class: "mx-auto mt-8 mb-0 max-w space-y-4") do
      - @section.option_definitions.each do |option|
        =render "option_form_#{option.type}" , section: @section , option: option
      -if @section.option_definitions.empty?
        %p No options
      -else
        = submit_button("Update")